spring:
  cloud:
    gateway:
      routes:
        - id: removeheader
          uri: http://localhost:8091
          predicates:
            - Path=/account/index/rewrite
          filters:
            - RemoveRequestHeader=beanId
        - id: addHeader
          uri: http://localhost:8091
          predicates:
            - Path=/account/index/rewrite
          filters:
            - AddRequestHeader=beanId, Bar
        - id: first
          uri: http://localhost:8091
          predicates:
            - Path=/account/index/**
service:
  url: http://127.0.0.1:8091
  name: account


logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


rsa:
  privateKey:
    path: pem/rsa_private_key_2048.pem
  publicKey:
    path: pem/rsa_public_key_2048.pem

jwt:
  token:
    exp: 2
  reToken:
    exp: 720

