server:
  port: 8090
#  servlet:
#    context-path: /gtw

spring:
  cloud:
    gateway:
      routes:
        - id: first
          uri: http://localhost:8091
          predicates:
            - Path=/account/index/**
#        - id: second
#          uri: http://localhost:8090
#          predicates:
#            - Path=/gtw/index/test

logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug


rsa:
  privateKey:
    path: pem/rsa_private_key_2048.pem
  publicKey:
    path: pem/rsa_public_key_2048.pem

jwt:
  token:
    exp: 2
  reToken:
    exp: 720